services:
  app:
    image: ghcr.io/cus-study-web/backend:latest
    container_name: studyweb-backend
    env_file:
      - backend.env
    expose:
      - "${BACKEND_PORT}:${SERVER_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_SERVER}:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
    restart: unless-stopped

  nginx:
    image: docker.io/library/nginx:alpine
    container_name: studyweb-nginx
    ports:
      - "${HTTP_PORT}:80"
    environment:
      SERVER_NAME: ${ALLOWED_SERVER}
    volumes:
      - ./nginx/default.conf:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - studyweb-network

networks:
  studyweb-network:
    external: true

