services:
  app:
    image: ghcr.io/cus-study-web/backend:latest
    container_name: studyweb-backend
    env_file:
      - backend.env
    ports:
      - "${BACKEND_PORT}:${SERVER_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DATABASE_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
    restart: unless-stopped

networks:
  studyweb-network:
    external: true

